# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: hg38
  - /optimizer: adamw
  - /scheduler: cosine_warmup
  - /callbacks: [base, checkpoint, rich, wandb]

train:
  monitor: val/loss
  mode: min

task:
  _name_: lm
  loss: cross_entropy
  torchmetrics: ['perplexity', 'num_tokens']
  metrics:
    - accuracy

encoder: null
decoder: null
